name: compression-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate artifacts
      run: |
        rmm="test_value"
        echo "VAR=${rmm}" >> "${GITHUB_OUTPUT}"
        echo "REPO is ${{ github.repository }}"
      id: set
    - name: Using output substitution
      run: |
        echo "TEST=${{ steps.set.outputs.VAR }}_lib"
    - name: Downloading artifact from a different repo
      run: |
          printenv GH_TOKEN
          printenv GITHUB_RUN_ID
          mkdir temp
          gh run download 13291957457 --repo rapidsai/rmm --name rmm_conda_cpp_cuda11_aarch64 --dir temp
          ls temp
      env:
        GH_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN != '' && secrets.PRIVATE_GH_TOKEN || secrets.GITHUB_TOKEN }}
    # - name: upload artifact compression 3
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "artifact-3"
    #     path: "artifact.bin"
    #     compression-level: 3
    # - name: upload artifact compression 6
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "artifact-6"
    #     path: "artifact.bin"
    #     compression-level: 6
    # - name: upload artifact compression 9
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "artifact-9"
    #     path: "artifact.bin"
    #     compression-level: 9
