name: compression-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate artifacts
      run: |
        echo "rmm=test_value"
        echo "VAR=${rmm}" >> "${GITHUB_OUTPUT}"
      id: set
    - name: Using output substitution
      run: |
        echo "TEST=${{ steps.set.outputs.VAR }}_lib"
    # - name: upload artifact compression 3
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "artifact-3"
    #     path: "artifact.bin"
    #     compression-level: 3
    # - name: upload artifact compression 6
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "artifact-6"
    #     path: "artifact.bin"
    #     compression-level: 6
    # - name: upload artifact compression 9
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "artifact-9"
    #     path: "artifact.bin"
    #     compression-level: 9
